#!/usr/bin/env python3
"""Block direct edits to CLAUDE.md/AGENTS.md unless the source is also staged.

These files are auto-generated by scripts/build_agent_docs.py from docs/AGENTS.src.md.
Direct edits will be overwritten. Kept in Python (not bash) so the pre-commit hook runs
anywhere `uv run python` does, without depending on a POSIX shell.

Used by the pre-commit hook: agent-docs-no-direct-edit.
"""

import subprocess
import sys

GENERATED = {"CLAUDE.md", "AGENTS.md"}
SOURCES = {"docs/AGENTS.src.md", "scripts/build_agent_docs.py"}


def main() -> int:
    # NUL-delimited so paths with spaces/tabs parse correctly.
    staged = set(
        subprocess.run(
            ["git", "diff", "--cached", "--name-only", "-z"],
            capture_output=True,
            text=True,
            check=True,
        ).stdout.split("\0")
    )
    staged.discard("")

    # Nothing to check unless a generated file is actually staged.
    if not (GENERATED & staged):
        return 0

    # Allowed: the source or build script is staged too (the outputs were regenerated).
    if SOURCES & staged:
        return 0

    print("Error: CLAUDE.md and AGENTS.md are auto-generated.")
    print("Edit docs/AGENTS.src.md instead, then run: make agent-docs")
    return 1


if __name__ == "__main__":
    sys.exit(main())
